export const questions = {
    jedzonko: [
        { question: 'Małe jedzonko?', tags: ['małe'] },
        { question: 'Duże jedzonko?', tags: ['duże'] },
        { question: 'Coś słodkiego?', tags: ['słodkie'] },
        { question: 'Zdrowe jedzonko?', tags: ['zdrowe'] },
        { question: 'Niezdrowe jedzonko?', tags: ['niezdrowe'] },
        { question: 'Chcesz coś zamówić?', tags: ['na wynos'] },
        { question: 'Coś włoskiego?', tags: ['włoskie'] },
        { question: 'Coś domowego?', tags: ['domowe'] },
        { question: 'Coś do picia?', tags: ['napój'] },
        { question: 'Śniadanko?', tags: ['śniadanie'] },
        { question: 'Jakieś zupsko?', tags: ['zupa'] },
        { question: 'Coś na ciepło?', tags: ['ciepłe'] },
        { question: 'Coś na zimno?', tags: ['zimne'] },
        { question: 'Coś azjatyckiego?', tags: ['azjatyckie'] },
        { question: 'Coś meksykańskiego?', tags: ['meksykańskie'] },
    ],
    rozrywka: [
        { question: 'Masz ochotę na przygodę?', tags: ['przygoda'] },
        { question: 'Mam cię gdzieś zabrać?', tags: ['wyjście'] },
        { question: 'Czujesz się leniuszkiem?', tags: ['leniuchowanie'] },
        { question: 'Chcesz w coś zagrać?', tags: ['gry'] },
        { question: 'Chcesz coś obejrzeć?', tags: ['film'] },
        { question: 'Coś romantycznego?', tags: ['romantyczne'] },
        { question: 'Coś kreatywnego?', tags: ['kreatywne'] },
        { question: 'Coś ekscytującego?', tags: ['ekscytacja'] },
        { question: 'Chcesz mnie podręczyć?', tags: ['dręczenie'] },
        { question: 'Masz ochotę się poruszać?', tags: ['ruch'] },
        { question: 'Mam cie zaskoczyć?', tags: ['niespodzianka'] },
        { question: 'Chcesz rywalizować?', tags: ['rywalizacja'] },
        { question: 'Coś niedorzecznego?', tags: ['niedorzeczne'] },
    ],
    relaksik: [
        { question: 'Może czegoś posłuchamy?', tags: ['muzyka'] },
        { question: 'Czujesz spanko?', tags: ['sen'] },
        { question: 'Potrzebujesz się odprężyć?', tags: ['spa'] },
        { question: 'Potrzebujesz się wyciszyć?', tags: ['cisza'] },
        { question: 'Czy bolą Cię plecki?', tags: ['masaż', 'plecy'] },
        { question: 'Może coś do czytania?', tags: ['czytanie'] },
        { question: 'Chcesz coś obejrzeć?', tags: ['film'] },
        { question: 'Chcesz zrzucić ciuszki?', tags: ['nagość'] },
        { question: 'Czy bolą Cię stópki?', tags: ['stopy', 'masaż'] },
        { question: 'Masz ochotę się poruszać?', tags: ['ruch'] },
        { question: 'Coś niedorzecznego?', tags: ['niedorzeczne'] },
        { question: 'Czujesz się leniuszkiem?', tags: ['leniuchowanie'] },
    ],
};
